# Generated by Django 4.1.1 on 2022-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_banners/', verbose_name='Biz barada suraty')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Birinji setir')),
                ('title_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ikinji setir')),
                ('title_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Üçinji setir')),
            ],
            options={
                'verbose_name': 'Biz barada',
                'verbose_name_plural': 'Biz barada',
            },
        ),
    ]
