# Generated by Django 4.1.1 on 2022-11-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0002_aboutbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_3')),
            ],
            options={
                'verbose_name': 'Biz barada banner',
                'verbose_name_plural': 'Biz barada banner',
            },
        ),
    ]
