# Generated by Django 4.1.1 on 2022-11-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0003_aboutpagebanners'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Birinji setir')),
                ('title_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ikinji setir')),
                ('title_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Üçinji setir')),
                ('title_4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dördinji setir')),
                ('title_5', models.TextField(blank=True, null=True, verbose_name='Bäşinji setir')),
            ],
            options={
                'verbose_name': 'Biz barada maglumat',
                'verbose_name_plural': 'Biz barada maglumatlar',
            },
        ),
        migrations.AlterField(
            model_name='aboutpagebanners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Biz barada  suraty'),
        ),
        migrations.AlterField(
            model_name='aboutpagebanners',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Biz barada  suraty_2'),
        ),
        migrations.AlterField(
            model_name='aboutpagebanners',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Biz barada  suraty_3'),
        ),
    ]
