# Generated by Django 4.1.1 on 2022-11-20 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0004_aboutus_alter_aboutpagebanners_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ady')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icon/', verbose_name='Ikonkasy')),
            ],
            options={
                'verbose_name': 'Kategoriýa',
                'verbose_name_plural': 'Kategoriýalar',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Beýany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Suraty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ady'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_tm.category', verbose_name='Haýsy kategoriýa degişli'),
        ),
    ]
