# Generated by Django 4.1.1 on 2022-11-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0007_banner_big_image_2_banner_main_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='big_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Arkadaky surat'),
        ),
        migrations.AddField(
            model_name='banner',
            name='product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='product_tm.product', verbose_name='Haýsy haryda degişli'),
        ),
        migrations.AddField(
            model_name='banner',
            name='product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_3', to='product_tm.product', verbose_name='Haýsy haryda degişli'),
        ),
    ]
