# Generated by Django 4.1.1 on 2022-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0008_banner_big_image_3_banner_product_2_banner_product_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagebanners',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_4'),
        ),
    ]
