# Generated by Django 4.1.1 on 2022-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0009_mainpagebanners_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagebanners',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_5'),
        ),
    ]
