# Generated by Django 4.1.1 on 2022-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0012_product_image_2_product_image_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salgyňyz')),
                ('open_to_work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Işe başlaýan wagtyňyz')),
                ('close_to_work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Işi gutarýan wagtyňyz')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Telefon belgiňiz')),
                ('email', models.EmailField(max_length=50, verbose_name='E-poçtaňyz')),
            ],
            options={
                'verbose_name': 'Salgylar barada maglumat',
                'verbose_name_plural': 'Salgylar barada maglumatlar',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Aragatnaşyk formasy', 'verbose_name_plural': 'Aragatnaşyk formasy'},
        ),
    ]
