# Generated by Django 4.1.1 on 2022-11-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0013_locations_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_banner/', verbose_name='Harytlardaky banner')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beýan kiçi')),
                ('title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beýan uly')),
            ],
            options={
                'verbose_name': 'Harytlardaky banner',
                'verbose_name_plural': 'Harytlardaky bannerlar',
            },
        ),
    ]
