# Generated by Django 4.1.1 on 2022-11-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0014_productsbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='map',
            field=models.TextField(blank=True, null=True, verbose_name='Kartada ýerleşýän ýeriňiz'),
        ),
    ]
