# Generated by Django 4.1.1 on 2022-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0015_locations_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_banner/', verbose_name='Konataktdaky banner'),
        ),
    ]
