# Generated by Django 4.1.1 on 2022-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tm', '0016_locations_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.ImageField(blank=True, null=True, upload_to='ru_flag/')),
            ],
        ),
    ]
