# Generated by Django 4.1.1 on 2022-11-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_banners/', verbose_name='О нас фото')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Первая линия')),
                ('title_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вторая линия')),
                ('title_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Третья строка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutPageBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='О нас')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='О нас_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='О нас_3')),
            ],
            options={
                'verbose_name': 'Баннер о нас',
                'verbose_name_plural': 'Баннер о нас',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Первая строка')),
                ('title_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вторая линия')),
                ('title_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Третья строка')),
                ('title_4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Четвертая строка')),
                ('title_5', models.TextField(blank=True, null=True, verbose_name='Пятая линия')),
            ],
            options={
                'verbose_name': 'Информация о нас',
                'verbose_name_plural': 'Информация о нас',
            },
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='benefits/', verbose_name='Изображение достижений')),
                ('title', models.CharField(max_length=50, verbose_name='Имя достижения')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заявление о достижениях')),
            ],
            options={
                'verbose_name': 'Успех',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icon/', verbose_name='значок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.ImageField(blank=True, null=True, upload_to='ru_flag/')),
                ('eng', models.ImageField(blank=True, null=True, upload_to='ru_flag/')),
                ('tm', models.ImageField(blank=True, null=True, upload_to='ru_flag/')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_banner/', verbose_name='Контактный баннер')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваш адрес')),
                ('open_to_work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Когда вы начнете работать')),
                ('close_to_work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Когда вы закончите работу')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Ваш номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Ваш адрес электронной почты')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Ваше местоположение на карте')),
            ],
            options={
                'verbose_name': 'Справочная информация',
                'verbose_name_plural': 'Справочная информация',
            },
        ),
        migrations.CreateModel(
            name='MainPageBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Фото')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Фото_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Фото_3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Фото_4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Фото_5')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Фото')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Фото_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Фото_3')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_ru.category', verbose_name='К какой категории относится?')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_banner/', verbose_name='Баннер на товары')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заявление маленькое')),
                ('title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заявление отличное')),
            ],
            options={
                'verbose_name': 'Баннер на товары',
                'verbose_name_plural': 'Баннер на товары',
            },
        ),
        migrations.CreateModel(
            name='TopThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_ru.product', verbose_name='В какому продукту он принадлежит')),
            ],
            options={
                'verbose_name': 'Популярный товар',
                'verbose_name_plural': 'Самые популярные товары',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('big_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Фото сзади')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Основное изображение')),
                ('name_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('title_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('big_image_2', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Фото сзади')),
                ('main_image_2', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Основное изображение')),
                ('name_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('title_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('big_image_3', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Фото сзади')),
                ('main_image_3', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Основное изображение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_ru.product', verbose_name='В какому продукту он принадлежит')),
                ('product_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='product_ru.product', verbose_name='В какому продукту он принадлежит')),
                ('product_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_3', to='product_ru.product', verbose_name='В какому продукту он принадлежит')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
