# Generated by Django 4.1.1 on 2022-11-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_banners/', verbose_name='Biz barada suraty')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Birinji setir')),
                ('title_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ikinji setir')),
                ('title_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Üçinji setir')),
            ],
            options={
                'verbose_name': 'Biz barada',
                'verbose_name_plural': 'Biz barada',
            },
        ),
        migrations.CreateModel(
            name='AboutPageBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Biz barada  suraty')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Biz barada  suraty_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Biz barada  suraty_3')),
            ],
            options={
                'verbose_name': 'Biz barada banner',
                'verbose_name_plural': 'Biz barada banner',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Birinji setir')),
                ('title_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ikinji setir')),
                ('title_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Üçinji setir')),
                ('title_4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dördinji setir')),
                ('title_5', models.TextField(blank=True, null=True, verbose_name='Bäşinji setir')),
            ],
            options={
                'verbose_name': 'Biz barada maglumat',
                'verbose_name_plural': 'Biz barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='benefits/', verbose_name='Üstünlikleriň suraty')),
                ('title', models.CharField(max_length=50, verbose_name='Üstünlikleriň ady')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Üstünlikleriň beýany')),
            ],
            options={
                'verbose_name': 'Üstünlik',
                'verbose_name_plural': 'Üstünlikler',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ady')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icon/', verbose_name='Ikonkasy')),
            ],
            options={
                'verbose_name': 'Kategoriýa',
                'verbose_name_plural': 'Kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aragatnaşyk formasy',
                'verbose_name_plural': 'Aragatnaşyk formasy',
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.ImageField(blank=True, null=True, upload_to='ru_flag/')),
                ('eng', models.ImageField(blank=True, null=True, upload_to='ru_flag/')),
                ('tm', models.ImageField(blank=True, null=True, upload_to='ru_flag/')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_banner/', verbose_name='Konataktdaky banner')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salgyňyz')),
                ('open_to_work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Işe başlaýan wagtyňyz')),
                ('close_to_work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Işi gutarýan wagtyňyz')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Telefon belgiňiz')),
                ('email', models.EmailField(max_length=50, verbose_name='E-poçtaňyz')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Kartada ýerleşýän ýeriňiz')),
            ],
            options={
                'verbose_name': 'Salgylar barada maglumat',
                'verbose_name_plural': 'Salgylar barada maglumatlar',
            },
        ),
        migrations.CreateModel(
            name='MainPageBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='main_page_banners/', verbose_name='Üstunlikleriň suraty_5')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Täzelik',
                'verbose_name_plural': 'Täzelikler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ady')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Suraty')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Suraty_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Suraty_3')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Beýany')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_eng.category', verbose_name='Haýsy kategoriýa degişli')),
            ],
            options={
                'verbose_name': 'Haryt',
                'verbose_name_plural': 'harytlar',
            },
        ),
        migrations.CreateModel(
            name='ProductsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_banner/', verbose_name='Harytlardaky banner')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beýan kiçi')),
                ('title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beýan uly')),
            ],
            options={
                'verbose_name': 'Harytlardaky banner',
                'verbose_name_plural': 'Harytlardaky bannerlar',
            },
        ),
        migrations.CreateModel(
            name='TopThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_eng.product')),
            ],
            options={
                'verbose_name': 'Meşhur haryt',
                'verbose_name_plural': 'Iň meşhur harytlar',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ady')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Beýany')),
                ('big_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Arkadaky surat')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Esasy surat')),
                ('name_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ady')),
                ('title_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Beýany')),
                ('big_image_2', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Arkadaky surat')),
                ('main_image_2', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Esasy surat')),
                ('name_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ady')),
                ('title_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Beýany')),
                ('big_image_3', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Arkadaky surat')),
                ('main_image_3', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Esasy surat')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_eng.product', verbose_name='Haýsy haryda degişli')),
                ('product_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='product_eng.product', verbose_name='Haýsy haryda degişli')),
                ('product_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_3', to='product_eng.product', verbose_name='Haýsy haryda degişli')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
    ]
